#!/bin/bash
cd '../out'
#load reference sequences into QIIME
qiime tools import --input-path ../out/stripped.fq --output-path ../out/stripped.qza --type "RawSequences"
#load OTU sequences into QIIME
qiime tools import --input-path otus.fa --output-path otus.qza --type "FeatureData[Sequence]"
#load reference database into QIIME
#qiime tools import --input-path ../reference/ref.fa --output-path ref.qza --type "FeatureData[Sequence]"

#Assign taxonomy
qiime feature-classifier classify-consensus-blast \
--i-query otus.qza --i-reference-reads stripped.qza \
--i-reference-taxonomy ../reference/ref.fa \
--p-strand plus \
--o-classification taxonomy.qza \