#!/bin/bash
cd ..

rm -f -r out/*						# remove out folder and its contents
rm -f -r export/*					# remove export folder and its
mkdir out                           # create out folder
mkdir export                        # create export folder
mkdir fastqc                        # create fastqc folder