#!/bin/bash

echo "FASTQC - Project directory is: fq/"${active_dir}
cd '../fq/'${active_dir}

# Pool all forward and all reverse reads separately to assess quality in fastqc
cat *_R1*.fastq >> ../../fastqc/${active_dir}/forward_reads.fastq
cat *_R2*.fastq >> ../../fastqc/${active_dir}/reverse_reads.fastq 

cd '../../'fastqc/${active_dir}
# Run fastqc on these files
fastqc forward_reads.fastq  
fastqc reverse_reads.fastq  
 
# cd '../../scripts'