#!/bin/bash

#define folder name
echo "Enter fq/<foldername>:"
read dir
echo "Project directory is: fq/"${dir}
cd '../fq/'${dir}
rm -f -r fastqc

# Pool all forward and all reverse reads separately to assess quality in fastqc
mkdir fastqc
chmod +744 fastqc



cat *_R1*.fastq >> fastqc/forward_reads.fastq
cat *_R2*.fastq >> fastqc/reverse_reads.fastq 

# Run fastqc on these files
fastqc fastqc/forward_reads.fastq  
fastqc fastqc/reverse_reads.fastq  