#!/bin/bash
echo "FastQC - Enter fq/ foldername:"
read x
cd '../fq/'${x}
rm -f -r fastqc

# Pool all forward and all reverse reads separately to assess quality in fastqc
mkdir fastqc
chmod +744 fastqc



cat *_R1*.fastq >> fastqc/forward_reads.fastq
cat *_R2*.fastq >> fastqc/reverse_reads.fastq 

# Run fastqc on these files
fastqc fastqc/forward_reads.fastq  
fastqc fastqc/reverse_reads.fastq  