#!/bin/bash
cd '../fq/'${active_dir}
echo "USEARCH - Project directory is: fq/"${active_dir}
$usearch -fastq_mergepairs *_R1*.fastq  -relabel @ \
	-fastq_maxdiffs 5 -fastq_pctid 5 \
	-fastq_minmergelen 80 -fastq_maxmergelen 300 \
	-fastqout ../../out/${active_dir}/merged.fq \
	-report ../../out/${active_dir}/merge.log