#!/bin/bash
#stage 1 primers, F = 59bp, R = 59 incl indexing binding sites
#stage 1 primers F 26 R 25 without binding sites
cd ../out/${active_dir}
echo "Forward primer is ${fwd_primer}bp long"
echo "Reverse primer is ${rev_primer}bp long"

$usearch -fastx_truncate merged.fq -stripleft ${fwd_primer} -stripright ${rev_primer} \
  -fastqout stripped.fq 
  #outfile called merge not strip so I can selectively turn off the strip at pipeline to see the impact
