#!/bin/bash
#stage 1 primers, F = 59bp, R = 59 incl indexing binding sites
#stage 1 primers F 26 R 25 without binding sites
$usearch -fastx_truncate ../out/merged.fq -stripleft 26 -stripright 25 \
  -fastqout ../out/stripped.fq 
  #outfile called merge not strip so I can selectively turn off the strip at pipeline to see the impact