#!/bin/bash
cd '../out/'${active_dir}
# Make raw OTU table 97%
$usearch -otutab merged.fq -db otus.fa \
-strand plus -id 0.97 -otutabout otu_table.txt

#make ZOTU table 99%
$usearch -otutab merged.fq -db zotus.fa \
-strand plus -id 0.99 -otutabout zotu_table.txt

