#!/bin/bash
cd '../out/'${active_dir}

echo "USEARCH taxonomy assignment using" ${refdb}
# Predict otu taxonomy - my custom db 0.8?
$usearch -sintax otus.fa -db ../../reference/${refdb} -strand both \
 -tabbedout otusintax.txt -sintax_cutoff 0.9
# Predict asv taxonomy - my custom db 0.8?
$usearch -sintax zotus.fa -db ../../reference/${refdb} -strand both \
 -tabbedout zotusintax.txt -sintax_cutoff 0.9

#Predict otu taxonomy - with mitofish db
#usearch -sintax ../out/otus.fa -db ../reference/mitofish_complete_partial_v3.71.fa -strand both \
 #-tabbedout ../out/otusintax_mitofish.txt -sintax_cutoff 0.8
#Predict asv taxonomy - with mitofish db
#usearch -sintax ../out/zotus.fa -db ../reference/mitofish_complete_partial_v3.71.fa -strand both \
#-tabbedout ../out/zotusintax_mitofish.txt -sintax_cutoff 0.8

#check sintax cutoff / confidence scores

# Taxonomy summary reports - doesnt work cos 32bit
#usearch -sintax_summary ../out/sintax.txt -otutabin otutab_raw.txt -rank s -output ../out/sintax_summary.txt