#!/bin/bash
cd '../out'

#tables formatting
sed -i.tmp 's/#OTU ID//' otu_table.txt
sed -i.tmp 's/#OTU ID//' zotu_table.txt

#export tables
cp otu_table.txt ../export/otu_table.txt
cp zotu_table.txt ../export/zotu_table.txt

#modify sintax files
cd '../out'
cut -f1 otusintax.txt > OTU_IDs
cut -f4 otusintax.txt > raw_tax
cut -d : -f2 raw_tax | cut -d , -f1 | sed 's/\"//g' > family
cut -d : -f3 raw_tax | cut -d , -f1 | sed 's/\"//g' > species
paste OTU_IDs family species > tax_temp
echo -e "\totus\tfamily\tspecies\tspecies2" > header
cat header tax_temp > otusintax_formatted.txt
rm OTU_IDs raw_tax  family  species tax_temp header

cut -f1 zotusintax.txt > OTU_IDs
cut -f4 zotusintax.txt > raw_tax
cut -d : -f2 raw_tax | cut -d , -f1 | sed 's/\"//g' > family
cut -d : -f3 raw_tax | cut -d , -f1 | sed 's/\"//g' > species
paste OTU_IDs family species > tax_temp
echo -e "\totus\tfamily\tspecies\tspecies2" > header
cat header tax_temp > zotusintax_formatted.txt

#export sintax formatted for R
cp otusintax_formatted.txt ../export/otu_sintax.txt
cp zotusintax_formatted.txt ../export/zotu_sintax.txt

#export blastn results 
cp blast_otus.txt ../export/otu_blast.txt
cp blast_zotus.txt ../export/zotu_blast.txt

rm header