#!/bin/bash
#had to do a manual install of blast+ to get latest version
#this script is placed in the blast+ install directory inside the project folder
#nt database is 165gb and 
cd ../out
#blast otus
blastn -remote -db nt -evalue 1e-3 -perc_identity 92  -query otus.fa -out blast_otus.txt -outfmt "6 qseqid sseqid staxids sscinames scomnames sskingdoms pident length qlen slen mismatch gapopen gaps qstart qend sstart send stitle evalue bitscore qcovs qcovhsp" -max_target_seqs 10
